apiVersion: apps/v1
kind: Deployment
metadata:
  name: kittypong-game
  labels:
    app: kittypong-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kittypong-game
  template:
    metadata:
      labels:
        app: kittypong-game
    spec:
      containers:
      - name: kittypong-game
        image: kittypongacr.azurecr.io/3dkittypong:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: inline-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: inline-html
        configMap:
          name: kittypong-inline-html