apiVersion: v1
kind: Service
metadata:
  name: 3dkittypong-game-service
  labels:
    app: 3dkittypong-game
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: 3dkittypong-game