name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload dist.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist.zip

      - name: Download dist.zip artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist.zip