name: Deploy to AKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: kittypongacr.azurecr.io
  REPOSITORY: 3dkittypong-game
  IMAGE_TAG: ${{ github.sha }}
  AKS_CLUSTER_NAME: kittypong-aks
  AKS_RESOURCE_GROUP: 3DKittyPongAKS

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${REGISTRY%%.*}
    
    - name: Build and push Docker image
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker build -t $REGISTRY/$REPOSITORY:latest .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:latest
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME
    
    - name: Deploy to AKS
      run: |
        # Replace image tag placeholder with actual tag
        envsubst < k8s/deployment.yaml | kubectl apply -f -
        
        # Apply other Kubernetes manifests
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/configmap.yaml
        
        # Wait for deployment to complete
        kubectl rollout status deployment/kittypong-game --timeout=300s
    
    - name: Get service URL
      run: |
        echo "Getting service external IP..."
        kubectl get service kittypong-game-service